// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { OtpsControllerCreateOtpData, OtpsControllerCreateOtpResponses, PizzaControllerCancelPizzaOrderData, PizzaControllerCancelPizzaOrderResponses, PizzaControllerCreatePizzaPaymentData, PizzaControllerCreatePizzaPaymentResponses, PizzaControllerGetPizzaOrderData, PizzaControllerGetPizzaOrderResponses, PizzaControllerGetPizzaOrdersData, PizzaControllerGetPizzaOrdersResponses, PizzaControllerGetPizzasCatalogData, PizzaControllerGetPizzasCatalogResponses, UsersControllerSessionData, UsersControllerSessionResponses, UsersControllerSigninData, UsersControllerSigninResponses, UsersControllerUpdateProfileData, UsersControllerUpdateProfileResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Создание отп кода
 */
export const otpsControllerCreateOtp = <ThrowOnError extends boolean = false>(options: Options<OtpsControllerCreateOtpData, ThrowOnError>): RequestResult<OtpsControllerCreateOtpResponses, unknown, ThrowOnError> => (options.client ?? client).post<OtpsControllerCreateOtpResponses, unknown, ThrowOnError>({
    url: '/api/auth/otp',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Авторизация
 */
export const usersControllerSignin = <ThrowOnError extends boolean = false>(options: Options<UsersControllerSigninData, ThrowOnError>): RequestResult<UsersControllerSigninResponses, unknown, ThrowOnError> => (options.client ?? client).post<UsersControllerSigninResponses, unknown, ThrowOnError>({
    url: '/api/users/signin',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Обновить профиль пользователя
 */
export const usersControllerUpdateProfile = <ThrowOnError extends boolean = false>(options: Options<UsersControllerUpdateProfileData, ThrowOnError>): RequestResult<UsersControllerUpdateProfileResponses, unknown, ThrowOnError> => (options.client ?? client).patch<UsersControllerUpdateProfileResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/users/profile',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Получить сессию пользователя
 */
export const usersControllerSession = <ThrowOnError extends boolean = false>(options?: Options<UsersControllerSessionData, ThrowOnError>): RequestResult<UsersControllerSessionResponses, unknown, ThrowOnError> => (options?.client ?? client).get<UsersControllerSessionResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/users/session',
    ...options
});

/**
 * Получить пиццы
 */
export const pizzaControllerGetPizzasCatalog = <ThrowOnError extends boolean = false>(options?: Options<PizzaControllerGetPizzasCatalogData, ThrowOnError>): RequestResult<PizzaControllerGetPizzasCatalogResponses, unknown, ThrowOnError> => (options?.client ?? client).get<PizzaControllerGetPizzasCatalogResponses, unknown, ThrowOnError>({ url: '/api/pizza/catalog', ...options });

/**
 * Оплатить корзину
 */
export const pizzaControllerCreatePizzaPayment = <ThrowOnError extends boolean = false>(options: Options<PizzaControllerCreatePizzaPaymentData, ThrowOnError>): RequestResult<PizzaControllerCreatePizzaPaymentResponses, unknown, ThrowOnError> => (options.client ?? client).post<PizzaControllerCreatePizzaPaymentResponses, unknown, ThrowOnError>({
    url: '/api/pizza/payment',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Получить все заказы
 */
export const pizzaControllerGetPizzaOrders = <ThrowOnError extends boolean = false>(options?: Options<PizzaControllerGetPizzaOrdersData, ThrowOnError>): RequestResult<PizzaControllerGetPizzaOrdersResponses, unknown, ThrowOnError> => (options?.client ?? client).get<PizzaControllerGetPizzaOrdersResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/pizza/orders',
    ...options
});

/**
 * Получить заказ
 */
export const pizzaControllerGetPizzaOrder = <ThrowOnError extends boolean = false>(options: Options<PizzaControllerGetPizzaOrderData, ThrowOnError>): RequestResult<PizzaControllerGetPizzaOrderResponses, unknown, ThrowOnError> => (options.client ?? client).get<PizzaControllerGetPizzaOrderResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/pizza/orders/{orderId}',
    ...options
});

/**
 * Отменить заказ
 */
export const pizzaControllerCancelPizzaOrder = <ThrowOnError extends boolean = false>(options: Options<PizzaControllerCancelPizzaOrderData, ThrowOnError>): RequestResult<PizzaControllerCancelPizzaOrderResponses, unknown, ThrowOnError> => (options.client ?? client).put<PizzaControllerCancelPizzaOrderResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/pizza/orders/cancel',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
