// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type CreateOtpDto = {
    phone: string;
};

export type OtpResponse = {
    /**
     * Статус запроса
     */
    success: boolean;
    /**
     * Причина ошибки
     */
    reason?: string;
    /**
     * Время запроса повторного отп кода в мс
     */
    retryDelay: number;
};

export type SignInDto = {
    /**
     * Номер телефона
     */
    phone: string;
    /**
     * Отп код
     */
    code: number;
};

export type User = {
    /**
     * ID пользователя
     */
    _id: string;
    /**
     * Номер телефона
     */
    phone: string;
    /**
     * Имя
     */
    firstname?: string;
    /**
     * Отчество
     */
    middlename?: string;
    /**
     * Фамилия
     */
    lastname?: string;
    /**
     * Почта
     */
    email?: string;
    /**
     * Город
     */
    city?: string;
};

export type SignInResponse = {
    /**
     * Статус запроса
     */
    success: boolean;
    /**
     * Причина ошибки
     */
    reason?: string;
    /**
     * Пользователь
     */
    user: User;
    /**
     * Пользовательский токен
     */
    token: string;
};

export type UpdateProfileProfileDto = {
    /**
     * Имя
     */
    firstname?: string;
    /**
     * Отчество
     */
    middlename?: string;
    /**
     * Фамилия
     */
    lastname?: string;
    /**
     * Почта
     */
    email?: string;
    /**
     * Город
     */
    city?: string;
};

export type UpdateProfileDto = {
    /**
     * Данные пользователя
     */
    profile: UpdateProfileProfileDto;
    /**
     * Номер телефона
     */
    phone: string;
};

export type UpdateProfileResponse = {
    /**
     * Статус запроса
     */
    success: boolean;
    /**
     * Причина ошибки
     */
    reason?: string;
    /**
     * Пользователь
     */
    user: User;
};

export type SessionResponse = {
    /**
     * Статус запроса
     */
    success: boolean;
    /**
     * Причина ошибки
     */
    reason?: string;
    /**
     * Пользователь
     */
    user: User;
};

/**
 * Идентификатор ингредиента
 */
export type Ingredient = 'pineapple' | 'mozzarella' | 'pepperoni' | 'green_pepper' | 'mushrooms' | 'basil' | 'cheddar' | 'parmesan' | 'feta' | 'ham' | 'pickle' | 'tomato' | 'bacon' | 'onion' | 'chile' | 'shrimp' | 'chicken_fillet' | 'meatballs';

export type PizzaIngredient = {
    /**
     * Идентификатор ингредиента
     */
    type: Ingredient;
    /**
     * Цена ингредиента
     */
    price: number;
    /**
     * Изображение ингредиента
     */
    img: string;
};

/**
 * Идентификатор размера пиццы
 */
export type Size = 'small' | 'medium' | 'large';

export type PizzaSize = {
    /**
     * Идентификатор размера пиццы
     */
    type: Size;
    /**
     * Цена пиццы
     */
    price: number;
};

/**
 * Идентификатор типа теста
 */
export type Dough = 'thin' | 'thick';

export type PizzaDough = {
    /**
     * Идентификатор типа теста
     */
    type: Dough;
    /**
     * Цена теста
     */
    price: number;
};

export type Pizza = {
    /**
     * Идентификатор пиццы
     */
    id: string;
    /**
     * Название пиццы
     */
    name: string;
    /**
     * Ингредиенты
     */
    ingredients: Array<PizzaIngredient>;
    /**
     * Топпинги
     */
    toppings: Array<PizzaIngredient>;
    /**
     * Описание пиццы
     */
    description: string;
    /**
     * Размеры пиццы
     */
    sizes: Array<PizzaSize>;
    /**
     * Тип теста
     */
    doughs: Array<PizzaDough>;
    /**
     * Количество калорий
     */
    calories: number;
    /**
     * Количество белков
     */
    protein: string;
    /**
     * Количество жиров
     */
    totalFat: string;
    /**
     * Количество углеводов
     */
    carbohydrates: string;
    /**
     * Количество натрия
     */
    sodium: string;
    /**
     * Список аллергенов
     */
    allergens: Array<string>;
    /**
     * Для вегетарианцев
     */
    isVegetarian: boolean;
    /**
     * Наличие глютена
     */
    isGlutenFree: boolean;
    /**
     * Новинка
     */
    isNew: boolean;
    /**
     * Хит
     */
    isHit: boolean;
    /**
     * Изображение пиццы
     */
    img: string;
};

export type PizzasResponse = {
    /**
     * Статус запроса
     */
    success: boolean;
    /**
     * Причина ошибки
     */
    reason?: string;
    /**
     * Пиццы
     */
    catalog: Array<Pizza>;
};

export type CreatePizzaPaymentAddressDto = {
    /**
     * Улица
     */
    street: string;
    /**
     * Номер дома
     */
    house: string;
    /**
     * Номер квартиры
     */
    apartment: string;
    /**
     * Комментарий
     */
    comment?: string;
};

export type CreatePizzaPaymentPersonDto = {
    /**
     * Имя
     */
    firstname: string;
    /**
     * Фамилия
     */
    lastname: string;
    /**
     * Отчество
     */
    middlename?: string;
    /**
     * Телефон
     */
    phone: string;
};

export type CreatePizzaPaymentDebitCardDto = {
    /**
     * Номер карты
     */
    pan: string;
    /**
     * Срок действие карты
     */
    expireDate: string;
    /**
     * Код карты
     */
    cvv: string;
};

export type OrderedPizza = {
    /**
     * Идентификатор пиццы
     */
    id: string;
    /**
     * Топпинги
     */
    toppings: Array<Ingredient>;
    /**
     * Размер пиццы
     */
    size: Size;
    /**
     * Тип теста
     */
    dough: Dough;
};

export type CreatePizzaPaymentDto = {
    /**
     * Адрес доставки
     */
    receiverAddress: CreatePizzaPaymentAddressDto;
    /**
     * Данные пользователя
     */
    person: CreatePizzaPaymentPersonDto;
    /**
     * Банковская карта
     */
    debitCard: CreatePizzaPaymentDebitCardDto;
    /**
     * Пиццы
     */
    pizzas: Array<OrderedPizza>;
};

export type PizzaPerson = {
    /**
     * Имя
     */
    firstname: string;
    /**
     * Фамилия
     */
    lastname: string;
    /**
     * Отчество
     */
    middlename: string;
    /**
     * Телефон
     */
    phone: string;
};

export type PizzaAddress = {
    /**
     * Улица
     */
    street: string;
    /**
     * Номер дома
     */
    house: string;
    /**
     * Номер квартиры
     */
    apartment: string;
    /**
     * Комментарий
     */
    comment: string;
};

/**
 * Статус доставки
 */
export type PizzaStatus = 'in_processing' | 'waiting_courier' | 'on_my_way' | 'success' | 'canceled';

export type PizzaOrder = {
    /**
     * ID заказа
     */
    _id: string;
    /**
     * Пиццы
     */
    pizzas: Array<Pizza>;
    /**
     * Сумма заказа
     */
    totalPrice: number;
    /**
     * Данные пользователя
     */
    person: PizzaPerson;
    /**
     * Адрес доставки
     */
    receiverAddress: PizzaAddress;
    /**
     * Статус доставки
     */
    status: PizzaStatus;
    /**
     * Статус отмены
     */
    cancellable: boolean;
};

export type PizzaPaymentResponse = {
    /**
     * Статус запроса
     */
    success: boolean;
    /**
     * Причина ошибки
     */
    reason?: string;
    /**
     * Доставка
     */
    order: PizzaOrder;
};

export type PizzaOrdersResponse = {
    /**
     * Статус запроса
     */
    success: boolean;
    /**
     * Причина ошибки
     */
    reason?: string;
    /**
     * Доставки
     */
    orders: Array<PizzaOrder>;
};

export type PizzaOrderResponse = {
    /**
     * Статус запроса
     */
    success: boolean;
    /**
     * Причина ошибки
     */
    reason?: string;
    /**
     * Доставки
     */
    order: PizzaOrder;
};

export type CancelPizzaOrderDto = {
    /**
     * Идентификатор заказа
     */
    orderId: string;
};

export type BaseResponse = {
    /**
     * Статус запроса
     */
    success: boolean;
    /**
     * Причина ошибки
     */
    reason?: string;
};

export type OtpsControllerCreateOtpData = {
    body: CreateOtpDto;
    path?: never;
    query?: never;
    url: '/api/auth/otp';
};

export type OtpsControllerCreateOtpResponses = {
    /**
     * create otp
     */
    200: OtpResponse;
};

export type OtpsControllerCreateOtpResponse = OtpsControllerCreateOtpResponses[keyof OtpsControllerCreateOtpResponses];

export type UsersControllerSigninData = {
    body: SignInDto;
    path?: never;
    query?: never;
    url: '/api/users/signin';
};

export type UsersControllerSigninResponses = {
    /**
     * signin
     */
    200: SignInResponse;
};

export type UsersControllerSigninResponse = UsersControllerSigninResponses[keyof UsersControllerSigninResponses];

export type UsersControllerUpdateProfileData = {
    body: UpdateProfileDto;
    headers?: {
        authorization?: string;
    };
    path?: never;
    query?: never;
    url: '/api/users/profile';
};

export type UsersControllerUpdateProfileResponses = {
    /**
     * update profile
     */
    200: UpdateProfileResponse;
};

export type UsersControllerUpdateProfileResponse = UsersControllerUpdateProfileResponses[keyof UsersControllerUpdateProfileResponses];

export type UsersControllerSessionData = {
    body?: never;
    headers?: {
        authorization?: string;
    };
    path?: never;
    query?: never;
    url: '/api/users/session';
};

export type UsersControllerSessionResponses = {
    /**
     * session
     */
    200: SessionResponse;
};

export type UsersControllerSessionResponse = UsersControllerSessionResponses[keyof UsersControllerSessionResponses];

export type PizzaControllerGetPizzasCatalogData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/pizza/catalog';
};

export type PizzaControllerGetPizzasCatalogResponses = {
    /**
     * catalog
     */
    200: PizzasResponse;
};

export type PizzaControllerGetPizzasCatalogResponse = PizzaControllerGetPizzasCatalogResponses[keyof PizzaControllerGetPizzasCatalogResponses];

export type PizzaControllerCreatePizzaPaymentData = {
    body: CreatePizzaPaymentDto;
    path?: never;
    query?: never;
    url: '/api/pizza/payment';
};

export type PizzaControllerCreatePizzaPaymentResponses = {
    /**
     * payment
     */
    200: PizzaPaymentResponse;
};

export type PizzaControllerCreatePizzaPaymentResponse = PizzaControllerCreatePizzaPaymentResponses[keyof PizzaControllerCreatePizzaPaymentResponses];

export type PizzaControllerGetPizzaOrdersData = {
    body?: never;
    headers?: {
        authorization?: string;
    };
    path?: never;
    query?: never;
    url: '/api/pizza/orders';
};

export type PizzaControllerGetPizzaOrdersResponses = {
    /**
     * orders
     */
    200: PizzaOrdersResponse;
};

export type PizzaControllerGetPizzaOrdersResponse = PizzaControllerGetPizzaOrdersResponses[keyof PizzaControllerGetPizzaOrdersResponses];

export type PizzaControllerGetPizzaOrderData = {
    body?: never;
    headers?: {
        authorization?: string;
    };
    path: {
        /**
         * Идентификатор заказа
         */
        orderId: string;
    };
    query?: never;
    url: '/api/pizza/orders/{orderId}';
};

export type PizzaControllerGetPizzaOrderResponses = {
    /**
     * order
     */
    200: PizzaOrderResponse;
};

export type PizzaControllerGetPizzaOrderResponse = PizzaControllerGetPizzaOrderResponses[keyof PizzaControllerGetPizzaOrderResponses];

export type PizzaControllerCancelPizzaOrderData = {
    body: CancelPizzaOrderDto;
    headers?: {
        authorization?: string;
    };
    path?: never;
    query?: never;
    url: '/api/pizza/orders/cancel';
};

export type PizzaControllerCancelPizzaOrderResponses = {
    /**
     * order cancel
     */
    200: BaseResponse;
};

export type PizzaControllerCancelPizzaOrderResponse = PizzaControllerCancelPizzaOrderResponses[keyof PizzaControllerCancelPizzaOrderResponses];
