// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zCreateOtpDto = z.object({
    phone: z.string()
});

export const zOtpResponse = z.object({
    success: z.boolean(),
    reason: z.string().optional(),
    retryDelay: z.number()
});

export const zSignInDto = z.object({
    phone: z.string(),
    code: z.number()
});

export const zUser = z.object({
    _id: z.string(),
    phone: z.string(),
    firstname: z.string().optional(),
    middlename: z.string().optional(),
    lastname: z.string().optional(),
    email: z.string().optional(),
    city: z.string().optional()
});

export const zSignInResponse = z.object({
    success: z.boolean(),
    reason: z.string().optional(),
    user: zUser,
    token: z.string()
});

export const zUpdateProfileProfileDto = z.object({
    firstname: z.string().optional(),
    middlename: z.string().optional(),
    lastname: z.string().optional(),
    email: z.string().optional(),
    city: z.string().optional()
});

export const zUpdateProfileDto = z.object({
    profile: zUpdateProfileProfileDto,
    phone: z.string()
});

export const zUpdateProfileResponse = z.object({
    success: z.boolean(),
    reason: z.string().optional(),
    user: zUser
});

export const zSessionResponse = z.object({
    success: z.boolean(),
    reason: z.string().optional(),
    user: zUser
});

/**
 * Идентификатор ингредиента
 */
export const zIngredient = z.enum([
    'pineapple',
    'mozzarella',
    'pepperoni',
    'green_pepper',
    'mushrooms',
    'basil',
    'cheddar',
    'parmesan',
    'feta',
    'ham',
    'pickle',
    'tomato',
    'bacon',
    'onion',
    'chile',
    'shrimp',
    'chicken_fillet',
    'meatballs'
]);

export const zPizzaIngredient = z.object({
    type: zIngredient,
    price: z.number(),
    img: z.string()
});

/**
 * Идентификатор размера пиццы
 */
export const zSize = z.enum([
    'small',
    'medium',
    'large'
]);

export const zPizzaSize = z.object({
    type: zSize,
    price: z.number()
});

/**
 * Идентификатор типа теста
 */
export const zDough = z.enum(['thin', 'thick']);

export const zPizzaDough = z.object({
    type: zDough,
    price: z.number()
});

export const zPizza = z.object({
    id: z.string(),
    name: z.string(),
    ingredients: z.array(zPizzaIngredient),
    toppings: z.array(zPizzaIngredient),
    description: z.string(),
    sizes: z.array(zPizzaSize),
    doughs: z.array(zPizzaDough),
    calories: z.number(),
    protein: z.string(),
    totalFat: z.string(),
    carbohydrates: z.string(),
    sodium: z.string(),
    allergens: z.array(z.string()),
    isVegetarian: z.boolean(),
    isGlutenFree: z.boolean(),
    isNew: z.boolean(),
    isHit: z.boolean(),
    img: z.string()
});

export const zPizzasResponse = z.object({
    success: z.boolean(),
    reason: z.string().optional(),
    catalog: z.array(zPizza)
});

export const zCreatePizzaPaymentAddressDto = z.object({
    street: z.string(),
    house: z.string(),
    apartment: z.string(),
    comment: z.string().optional()
});

export const zCreatePizzaPaymentPersonDto = z.object({
    firstname: z.string(),
    lastname: z.string(),
    middlename: z.string().optional(),
    phone: z.string()
});

export const zCreatePizzaPaymentDebitCardDto = z.object({
    pan: z.string(),
    expireDate: z.string(),
    cvv: z.string()
});

export const zOrderedPizza = z.object({
    id: z.string(),
    toppings: z.array(zIngredient),
    size: zSize,
    dough: zDough
});

export const zCreatePizzaPaymentDto = z.object({
    receiverAddress: zCreatePizzaPaymentAddressDto,
    person: zCreatePizzaPaymentPersonDto,
    debitCard: zCreatePizzaPaymentDebitCardDto,
    pizzas: z.array(zOrderedPizza)
});

export const zPizzaPerson = z.object({
    firstname: z.string(),
    lastname: z.string(),
    middlename: z.string(),
    phone: z.string()
});

export const zPizzaAddress = z.object({
    street: z.string(),
    house: z.string(),
    apartment: z.string(),
    comment: z.string()
});

/**
 * Статус доставки
 */
export const zPizzaStatus = z.enum([
    'in_processing',
    'waiting_courier',
    'on_my_way',
    'success',
    'canceled'
]);

export const zPizzaOrder = z.object({
    _id: z.string(),
    pizzas: z.array(zPizza),
    totalPrice: z.number(),
    person: zPizzaPerson,
    receiverAddress: zPizzaAddress,
    status: zPizzaStatus,
    cancellable: z.boolean()
});

export const zPizzaPaymentResponse = z.object({
    success: z.boolean(),
    reason: z.string().optional(),
    order: zPizzaOrder
});

export const zPizzaOrdersResponse = z.object({
    success: z.boolean(),
    reason: z.string().optional(),
    orders: z.array(zPizzaOrder)
});

export const zPizzaOrderResponse = z.object({
    success: z.boolean(),
    reason: z.string().optional(),
    order: zPizzaOrder
});

export const zCancelPizzaOrderDto = z.object({
    orderId: z.string()
});

export const zBaseResponse = z.object({
    success: z.boolean(),
    reason: z.string().optional()
});

export const zOtpsControllerCreateOtpBody = zCreateOtpDto;

/**
 * create otp
 */
export const zOtpsControllerCreateOtpResponse = zOtpResponse;

export const zUsersControllerSigninBody = zSignInDto;

/**
 * signin
 */
export const zUsersControllerSigninResponse = zSignInResponse;

export const zUsersControllerUpdateProfileBody = zUpdateProfileDto;

export const zUsersControllerUpdateProfileHeaders = z.object({
    authorization: z.string().optional()
});

/**
 * update profile
 */
export const zUsersControllerUpdateProfileResponse = zUpdateProfileResponse;

export const zUsersControllerSessionHeaders = z.object({
    authorization: z.string().optional()
});

/**
 * session
 */
export const zUsersControllerSessionResponse = zSessionResponse;

/**
 * catalog
 */
export const zPizzaControllerGetPizzasCatalogResponse = zPizzasResponse;

export const zPizzaControllerCreatePizzaPaymentBody = zCreatePizzaPaymentDto;

/**
 * payment
 */
export const zPizzaControllerCreatePizzaPaymentResponse = zPizzaPaymentResponse;

export const zPizzaControllerGetPizzaOrdersHeaders = z.object({
    authorization: z.string().optional()
});

/**
 * orders
 */
export const zPizzaControllerGetPizzaOrdersResponse = zPizzaOrdersResponse;

export const zPizzaControllerGetPizzaOrderHeaders = z.object({
    authorization: z.string().optional()
});

export const zPizzaControllerGetPizzaOrderPath = z.object({
    orderId: z.string()
});

/**
 * order
 */
export const zPizzaControllerGetPizzaOrderResponse = zPizzaOrderResponse;

export const zPizzaControllerCancelPizzaOrderBody = zCancelPizzaOrderDto;

export const zPizzaControllerCancelPizzaOrderHeaders = z.object({
    authorization: z.string().optional()
});

/**
 * order cancel
 */
export const zPizzaControllerCancelPizzaOrderResponse = zBaseResponse;
