// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { type Options, otpsControllerCreateOtp, pizzaControllerCancelPizzaOrder, pizzaControllerCreatePizzaPayment, pizzaControllerGetPizzaOrder, pizzaControllerGetPizzaOrders, pizzaControllerGetPizzasCatalog, usersControllerSession, usersControllerSignin, usersControllerUpdateProfile } from '../sdk.gen';
import type { OtpsControllerCreateOtpData, OtpsControllerCreateOtpResponse, PizzaControllerCancelPizzaOrderData, PizzaControllerCancelPizzaOrderResponse, PizzaControllerCreatePizzaPaymentData, PizzaControllerCreatePizzaPaymentResponse, PizzaControllerGetPizzaOrderData, PizzaControllerGetPizzaOrderResponse, PizzaControllerGetPizzaOrdersData, PizzaControllerGetPizzaOrdersResponse, PizzaControllerGetPizzasCatalogData, PizzaControllerGetPizzasCatalogResponse, UsersControllerSessionData, UsersControllerSessionResponse, UsersControllerSigninData, UsersControllerSigninResponse, UsersControllerUpdateProfileData, UsersControllerUpdateProfileResponse } from '../types.gen';

/**
 * Создание отп кода
 */
export const otpsControllerCreateOtpMutation = (options?: Partial<Options<OtpsControllerCreateOtpData>>): UseMutationOptions<OtpsControllerCreateOtpResponse, DefaultError, Options<OtpsControllerCreateOtpData>> => {
    const mutationOptions: UseMutationOptions<OtpsControllerCreateOtpResponse, DefaultError, Options<OtpsControllerCreateOtpData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await otpsControllerCreateOtp({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Авторизация
 */
export const usersControllerSigninMutation = (options?: Partial<Options<UsersControllerSigninData>>): UseMutationOptions<UsersControllerSigninResponse, DefaultError, Options<UsersControllerSigninData>> => {
    const mutationOptions: UseMutationOptions<UsersControllerSigninResponse, DefaultError, Options<UsersControllerSigninData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await usersControllerSignin({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Обновить профиль пользователя
 */
export const usersControllerUpdateProfileMutation = (options?: Partial<Options<UsersControllerUpdateProfileData>>): UseMutationOptions<UsersControllerUpdateProfileResponse, DefaultError, Options<UsersControllerUpdateProfileData>> => {
    const mutationOptions: UseMutationOptions<UsersControllerUpdateProfileResponse, DefaultError, Options<UsersControllerUpdateProfileData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await usersControllerUpdateProfile({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const usersControllerSessionQueryKey = (options?: Options<UsersControllerSessionData>) => createQueryKey('usersControllerSession', options);

/**
 * Получить сессию пользователя
 */
export const usersControllerSessionOptions = (options?: Options<UsersControllerSessionData>) => queryOptions<UsersControllerSessionResponse, DefaultError, UsersControllerSessionResponse, ReturnType<typeof usersControllerSessionQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await usersControllerSession({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: usersControllerSessionQueryKey(options)
});

export const pizzaControllerGetPizzasCatalogQueryKey = (options?: Options<PizzaControllerGetPizzasCatalogData>) => createQueryKey('pizzaControllerGetPizzasCatalog', options);

/**
 * Получить пиццы
 */
export const pizzaControllerGetPizzasCatalogOptions = (options?: Options<PizzaControllerGetPizzasCatalogData>) => queryOptions<PizzaControllerGetPizzasCatalogResponse, DefaultError, PizzaControllerGetPizzasCatalogResponse, ReturnType<typeof pizzaControllerGetPizzasCatalogQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await pizzaControllerGetPizzasCatalog({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: pizzaControllerGetPizzasCatalogQueryKey(options)
});

/**
 * Оплатить корзину
 */
export const pizzaControllerCreatePizzaPaymentMutation = (options?: Partial<Options<PizzaControllerCreatePizzaPaymentData>>): UseMutationOptions<PizzaControllerCreatePizzaPaymentResponse, DefaultError, Options<PizzaControllerCreatePizzaPaymentData>> => {
    const mutationOptions: UseMutationOptions<PizzaControllerCreatePizzaPaymentResponse, DefaultError, Options<PizzaControllerCreatePizzaPaymentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await pizzaControllerCreatePizzaPayment({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const pizzaControllerGetPizzaOrdersQueryKey = (options?: Options<PizzaControllerGetPizzaOrdersData>) => createQueryKey('pizzaControllerGetPizzaOrders', options);

/**
 * Получить все заказы
 */
export const pizzaControllerGetPizzaOrdersOptions = (options?: Options<PizzaControllerGetPizzaOrdersData>) => queryOptions<PizzaControllerGetPizzaOrdersResponse, DefaultError, PizzaControllerGetPizzaOrdersResponse, ReturnType<typeof pizzaControllerGetPizzaOrdersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await pizzaControllerGetPizzaOrders({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: pizzaControllerGetPizzaOrdersQueryKey(options)
});

export const pizzaControllerGetPizzaOrderQueryKey = (options: Options<PizzaControllerGetPizzaOrderData>) => createQueryKey('pizzaControllerGetPizzaOrder', options);

/**
 * Получить заказ
 */
export const pizzaControllerGetPizzaOrderOptions = (options: Options<PizzaControllerGetPizzaOrderData>) => queryOptions<PizzaControllerGetPizzaOrderResponse, DefaultError, PizzaControllerGetPizzaOrderResponse, ReturnType<typeof pizzaControllerGetPizzaOrderQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await pizzaControllerGetPizzaOrder({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: pizzaControllerGetPizzaOrderQueryKey(options)
});

/**
 * Отменить заказ
 */
export const pizzaControllerCancelPizzaOrderMutation = (options?: Partial<Options<PizzaControllerCancelPizzaOrderData>>): UseMutationOptions<PizzaControllerCancelPizzaOrderResponse, DefaultError, Options<PizzaControllerCancelPizzaOrderData>> => {
    const mutationOptions: UseMutationOptions<PizzaControllerCancelPizzaOrderResponse, DefaultError, Options<PizzaControllerCancelPizzaOrderData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await pizzaControllerCancelPizzaOrder({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
